In [1]:
import pandas as pd
import os

In [18]:
folder_path = '/Users/christsang/Desktop/mlb project/Sports/stolen_bases_new'

In [19]:
folder_path = 'stolen_bases_new'

In [20]:
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

In [21]:
csv_files

['2020.csv',
 '2021.csv',
 '2023.csv',
 '2022.csv',
 '2019.csv',
 '2018.csv',
 '2024.csv',
 '2015.csv',
 '2014.csv',
 '2016.csv',
 '2017.csv']

In [22]:
csv_list = []

for file in csv_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    csv_list.append(df)

mlb_df = pd.concat(csv_list, ignore_index=True)
mlb_df.to_csv('combined.csv', index=False)

In [9]:
mlb_df.head()

,Unnamed: 0,Start_Base,End_Base,Event,Respon_Pitcher,runner_id,runner_name,pitcher_id,pitcher_name,batter_id,...,pitch_hand,credit,credit_id,homeScore,awayScore,inning,isTopInning,Date,Action,Base
0,60,1B,NaN,Caught Stealing 2B,NaN,545341,Randal Grichuk,643338,Chad Green,543760,...,R,Gary Sánchez,596142,2,2,7,True,2021-04-01,Caught,2B
1,82,1B,2B,Stolen Base 2B,NaN,643565,Mike Tauchman,605447,Jordan Romano,457803,...,R,Danny Jansen,643376,2,2,9,False,2021-04-01,Stolen,2B
2,84,2B,3B,Stolen Base 3B,NaN,643565,Mike Tauchman,605447,Jordan Romano,640449,...,R,Danny Jansen,643376,2,2,9,False,2021-04-01,Stolen,3B
3,57,1B,2B,Stolen Base 2B,NaN,666185,Dylan Carlson,489334,Craig Stammen,425877,...,R,Austin Nola,543592,3,6,4,True,2020-09-30,Stolen,2B
4,83,2B,3B,Stolen Base 3B,NaN,502054,Tommy Pham,650893,Génesis Cabrera,543592,...,L,Yadier Molina,425877,4,6,6,False,2020-09-30,Stolen,3B

In [10]:
mlb_df.columns

Index(['Unnamed: 0', 'Start_Base', 'End_Base', 'Event', 'Respon_Pitcher',
       'runner_id', 'runner_name', 'pitcher_id', 'pitcher_name', 'batter_id',
       'batter_name', 'pitch_hand', 'credit', 'credit_id', 'homeScore',
       'awayScore', 'inning', 'isTopInning', 'Date', 'Action', 'Base'],
      dtype='object')

In [11]:
cleaned_mlb = mlb_df[[col for col in mlb_df.columns if col not in ['Unnamed: 0.1', 'Unnamed: 0',
                                                    'Respon_Pitcher']]]

In [12]:
cleaned_mlb.head()

,Start_Base,End_Base,Event,runner_id,runner_name,pitcher_id,pitcher_name,batter_id,batter_name,pitch_hand,credit,credit_id,homeScore,awayScore,inning,isTopInning,Date,Action,Base
0,1B,NaN,Caught Stealing 2B,545341,Randal Grichuk,643338,Chad Green,543760,Marcus Semien,R,Gary Sánchez,596142,2,2,7,True,2021-04-01,Caught,2B
1,1B,2B,Stolen Base 2B,643565,Mike Tauchman,605447,Jordan Romano,457803,Jay Bruce,R,Danny Jansen,643376,2,2,9,False,2021-04-01,Stolen,2B
2,2B,3B,Stolen Base 3B,643565,Mike Tauchman,605447,Jordan Romano,640449,Clint Frazier,R,Danny Jansen,643376,2,2,9,False,2021-04-01,Stolen,3B
3,1B,2B,Stolen Base 2B,666185,Dylan Carlson,489334,Craig Stammen,425877,Yadier Molina,R,Austin Nola,543592,3,6,4,True,2020-09-30,Stolen,2B
4,2B,3B,Stolen Base 3B,502054,Tommy Pham,650893,Génesis Cabrera,543592,Austin Nola,L,Yadier Molina,425877,4,6,6,False,2020-09-30,Stolen,3B

In [13]:
cleaned_mlb['credit'].unique(), cleaned_mlb['credit'].nunique()

(array(['Gary Sánchez', 'Danny Jansen', 'Austin Nola', 'Yadier Molina',
        'Willson Contreras', 'Curt Casali', 'Tyler Flowers',
        'Martín Maldonado', 'Jacob Nottingham', 'Yasmani Grandal',
        'Alex Avila', 'Sean Murphy', 'Austin Barnes', 'Tony Wolters',
        'Chance Sisco', 'Chad Wallach', 'Dustin Garneau', 'Joey Bart',
        'Tyler Heineman', 'Daulton Varsho', 'James McCann',
        "Travis d'Arnaud", 'Ryan Jeffers', 'Jeff Mathis', 'Salvador Perez',
        'Eric Haase', 'Pedro Severino', 'Jonah Heim', 'Kurt Suzuki',
        'Robinson Chirinos', 'Wilson Ramos', 'Jorge Alfaro', 'Max Stassi',
        'Kevin Plawecki', 'Jacob Stallings', 'Sandy León', 'Andrew Knapp',
        'Michael Pérez', 'Elias Díaz', 'Will Smith', 'Austin Romine',
        'Christian Vázquez', 'Yan Gomes', 'Victor Caratini',
        'Tucker Barnhart', 'Sam Huff', 'Carson Kelly', 'Luis Torrens',
        'Kevan Smith', 'Alejandro Kirk', 'J.T. Realmuto', 'Mike Zunino',
        'Anthony Bemboom', 'Joseph Odom', 'John Ryan Murphy',
        'Omar Narváez', 'Drew Butera', 'Roberto Pérez', 'Mitch Garver',
        'Rafael Marchán', 'Matt Wieters', 'Jason Castro',
        'Kyle Higashioka', 'Tyler Stephenson', 'Willians Astudillo',
        'Stephen Vogt', 'Austin Hedges', 'Grayson Greiner', 'Jose Trevino',
        'Caleb Joseph', 'Cam Gallagher', 'José Briceño', 'Erik Kratz',
        'Reese McGuire', 'Bryan Holaday', 'Ali Sánchez', 'Garrett Stubbs',
        'Meibrys Viloria', 'Beau Taylor', 'Brian Navarreto',
        'Josh Phegley', 'Keibert Ruiz', 'Manny Piña', 'Zack Collins',
        'Tomás Nido', 'Andrew Knizner', 'Francisco Mejía',
        'Ryan Lavarnway', 'Austin Allen', 'Francisco Cervelli',
        'Chadwick Tromp', 'Joe Hudson', 'Alex Jackson',
        'William Contreras', 'Rob Brantly', 'Taylor Ward', 'Rocky Gale',
        'MJ Melendez', 'Luke Maile', 'Austin Wynns', 'Tom Murphy',
        'Brian McCann', 'Welington Castillo', 'Juan Centeno',
        'Jonathan Lucroy', 'Aramis Garcia', 'Jake Rogers',
        'Tim Federowicz', 'Russell Martin', 'Dom Nuñez', 'John Hicks',
        'Nick Dini', 'Buster Posey', 'Raudy Read', 'René Rivera',
        'Chris Herrmann', 'Kyle Farmer', 'Chris Iannetta', 'Bobby Wilson',
        'Juan Graterol', 'Isiah Kiner-Falefa', 'Seby Zavala',
        'Nick Hundley', 'Taylor Davis', 'Nick Ciuffo', 'Jesús Sucre',
        'Blake Swihart', 'Hayden Senger', 'Webster Rivas', 'Nick Fortes',
        'Riley Adams', 'Cal Raleigh', 'Sebastián  Rivero', 'Payton Henry',
        'Yohel Pozo', 'Ben Rortvedt', 'Patrick Mazeika', 'Tres Barrera',
        'Connor Wong', 'Jose Lobaton', 'José Godoy', 'P.J. Higgins',
        'Yermín Mercedes', 'Luis Campusano', "Logan O'Hoppe",
        'Patrick Bailey', 'Gabriel Moreno', 'Iván Herrera', 'Logan Porter',
        'Carlos Pérez', 'Bo Naylor', 'Austin Wells', 'Jason Delay',
        'Korey Lee', 'Brett Sullivan', 'Tyler Soderstrom',
        'Endy Rodríguez', 'Christian Bethancourt', 'Francisco Alvarez',
        'Yainer Diaz', 'Blake Sabol', 'David Fry', 'Adley Rutschman',
        'René Pinto', 'Tyler Cropley', 'Shea Langeliers', 'Drew Millas',
        'Miguel Amaya', 'Jose Herrera', "Brian O'Keefe", 'Freddy Fermin',
        'Matt Thaiss', 'Henry Davis', 'Brian Serven', 'César Salazar',
        'Michael Papierski', 'Chris Okey', 'Cooper Hummel',
        'Mark Kolozsvary', 'Bryan Lavastida', 'Roberto Alvarez',
        'Rusber Estrada', 'Andy Yerzy', 'Xavier Fernández', 'Josh Crouch',
        'Mike Rivera', 'Ian Moller', 'Juan Garcia', 'David Freitas',
        'Roldani Baldwin', 'Colby Fitch', 'Devin Mesoraco', 'Raffy Lopez',
        'A.J. Ellis', 'Bruce Maxwell', 'Jett Bandy', 'Tomás Telis',
        'Andrew Susac', 'Francisco Peña', 'Mike Marjama', 'Chris Stewart',
        'Miguel Montero', 'Carlos Ruiz', 'Stuart Turner', 'Chris Gimenez',
        'A.J. Jimenez', 'Cameron Rupp', 'Brett Nicholas', 'Héctor Sánchez',
        'Evan Gattis', 'Mike Ohlman', 'Ryan Hanigan', 'Derek Norris',
        'Kyle Schwarber', 'Eric Fryer', 'Eduardo Escobar',
        'Tuffy Gosewisch', 'Geovany Soto', 'Jarrod Saltalamacchia',
        'Anthony Recker', 'Tyler Marlette', 'Matt McBride', 'Adam Moore',
        'Trevor Brown', 'Ramón Cabrera', 'Dioner Navarro', 'Josh Thole',
        'David Ross', 'A.J. Pierzynski', 'Alberto Rosario', 'Hank Conger',
        'Brayan Peña', 'Steve Clevenger', 'Wilkyns Jimenez',
        'Parker Berberet', 'Mac James', 'Drew Romo', 'Logan Driscoll',
        'Hunter Goodman', 'Pedro Pagés', 'Jhonny Pereda',
        'Chuckie Robinson', 'Hunter Feduccia', 'Dillon Dingler',
        'Adrian Del Castillo', 'Kyle McCann', 'Carlos Narvaez',
        'Grant Koch', 'Jakson Reetz', 'Óscar Hernández', 'Johnny Monell',
        'Michael McKenry', 'Carlos Corporán', 'Taylor Teagarden',
        'Tony Cruz', 'Ed Easley', 'Jordan Pacheco', 'Jhonatan Solano',
        'Brett Hayes', 'Wil Nieves', 'Tony Sanchez', 'J.C. Boscan',
        'José Yépez', 'Brandon Bantz', 'Joel Jimenez', 'René García',
        'Shawn Zarraga', 'Wilkin Castillo', 'Gerald Laird', 'Jack Murphy',
        'John Baker', 'Josmil Pinto', 'José Molina', 'Adrian Nieto',
        'Wilin Rosario', 'John Buck', 'Dan Butler', 'Jackson Williams',
        'Matt Pagnozzi', 'John Jaso', 'George Kottaras', 'Koyie Hill',
        'Eli Whiteside', 'Carlos Santana', 'Miguel Olivo',
        'J.P. Arencibia', 'Ryan Doumit'], dtype=object),
 287)

In [14]:
cleaned_mlb[cleaned_mlb['credit']=='A.J. Pierzynski'].shape

(351, 19)

In [15]:
catcher_names = cleaned_mlb['credit'].unique().tolist()

for catcher in catcher_names:
    catcher_df = cleaned_mlb.loc[cleaned_mlb['credit']==catcher]
    clean_catcher_name = str(catcher).replace(" ", "_") # can't have spaces between the names yo
    catcher_df.to_csv(f"{clean_catcher_name}.csv", index=False)

In [16]:
Pier = pd.read_csv('A.J._Pierzynski.csv')
Pier.shape

(351, 19)

In [17]:
Pier.head()

,Start_Base,End_Base,Event,runner_id,runner_name,pitcher_id,pitcher_name,batter_id,batter_name,pitch_hand,credit,credit_id,homeScore,awayScore,inning,isTopInning,Date,Action,Base
0,1B,2B,Stolen Base 2B,430637,Kelly Johnson,607231,John Gant,518595,Travis d'Arnaud,R,A.J. Pierzynski,150229,1,2,4,True,2016-09-10,Stolen,2B
1,1B,NaN,Caught Stealing 2B,572821,Brian Dozier,542432,José Ramirez,593871,Jorge Polanco,R,A.J. Pierzynski,150229,0,1,8,True,2016-08-16,Caught,2B
2,1B,NaN,Caught Stealing 2B,541650,Hernán Pérez,503444,Joel De La Cruz,543590,Kirk Nieuwenhuis,R,A.J. Pierzynski,150229,0,0,2,False,2016-08-10,Caught,2B
3,1B,2B,Stolen Base 2B,571697,Scooter Gennett,542432,José Ramirez,474892,Chris Carter,R,A.J. Pierzynski,150229,4,2,7,False,2016-08-10,Stolen,2B
4,1B,2B,Stolen Base 2B,541650,Hernán Pérez,547007,Rob Whalen,542979,Keon Broxton,R,A.J. Pierzynski,150229,1,1,2,False,2016-08-08,Stolen,2B