In [2]:
import numpy as np
import pandas as pd

In [12]:
# read csvs
df2000 = pd.read_csv('2000.csv')
df2001 = pd.read_csv('2001.csv')
df2002 = pd.read_csv('2002.csv')
df2003 = pd.read_csv('2003.csv')
df2004 = pd.read_csv('2004.csv')
df2005 = pd.read_csv('2005.csv')
df2006 = pd.read_csv('2006.csv')
df2007 = pd.read_csv('2007.csv')
df2008 = pd.read_csv('2008.csv')
df2009 = pd.read_csv('2009.csv')
df2010 = pd.read_csv('2010.csv')
df2011 = pd.read_csv('2011.csv')
df2012 = pd.read_csv('2012.csv')
df2013 = pd.read_csv('2013.csv')
df2014 = pd.read_csv('2014.csv')
df2015 = pd.read_csv('2015.csv')
df2016 = pd.read_csv('2016.csv')
df2017 = pd.read_csv('2017.csv')
df2018 = pd.read_csv('2018.csv')
df2019 = pd.read_csv('2019.csv')
df2020 = pd.read_csv('2020.csv')
df2021 = pd.read_csv('2021.csv')
df2022 = pd.read_csv('2022.csv')
df2023 = pd.read_csv('2023.csv')

In [14]:
# concat all dfs
df = pd.concat([df2000, df2001, df2002, df2003, df2004, df2005, df2006, df2007, df2008, df2009, df2010, df2011, df2012, df2013, df2014, df2015, df2016, df2017, df2018, df2019, df2020, df2021, df2022, df2023])
df.head()

,Unnamed: 0.1,Unnamed: 0,Start_Base,End_Base,Event,Respon_Pitcher,runner_id,runner_name,credit,homeScore,awayScore,inning,isTopInning,Date,Action,Base,Year
0,2,16,1B,NaN,Caught Stealing 2B,NaN,113240,David Dellucci,Scott Servais,0,0,2,False,2000-09-30,Caught,2B,2000
1,3,28,1B,2B,Stolen Base 2B,NaN,116423,Damian Jackson,Todd Hundley,1,4,3,False,2000-09-30,Stolen,2B,2000
2,4,43,1B,2B,Stolen Base 2B,NaN,114961,Tom Goodwin,Ben Davis,1,4,5,True,2000-09-30,Stolen,2B,2000
3,5,25,1B,2B,Stolen Base 2B,NaN,115174,Marquis Grissom,Mitch Meluskey,3,1,3,True,2000-09-30,Stolen,2B,2000
4,6,53,1B,2B,Stolen Base 2B,NaN,123743,Jose Vizcaino,Brook Fordyce,5,1,5,True,2000-09-30,Stolen,2B,2000

In [7]:
import pandas as pd
import os

folder_path = 'stolen_bases_new'

csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

df = pd.DataFrame()

for file in csv_files:
    
    d = pd.read_csv(f'{folder_path}/{file}')
    
    df = pd.concat([df, d])

In [8]:
# drop unneeded cols
df.drop(['Unnamed: 0', 'Respon_Pitcher'], axis = 1, inplace = True)
df.head()

,Start_Base,End_Base,Event,runner_id,runner_name,pitcher_id,pitcher_name,batter_id,batter_name,pitch_hand,credit,credit_id,homeScore,awayScore,inning,isTopInning,Date,Action,Base
0,1B,NaN,Caught Stealing 2B,545341,Randal Grichuk,643338,Chad Green,543760,Marcus Semien,R,Gary Sánchez,596142,2,2,7,True,2021-04-01,Caught,2B
1,1B,2B,Stolen Base 2B,643565,Mike Tauchman,605447,Jordan Romano,457803,Jay Bruce,R,Danny Jansen,643376,2,2,9,False,2021-04-01,Stolen,2B
2,2B,3B,Stolen Base 3B,643565,Mike Tauchman,605447,Jordan Romano,640449,Clint Frazier,R,Danny Jansen,643376,2,2,9,False,2021-04-01,Stolen,3B
3,1B,2B,Stolen Base 2B,666185,Dylan Carlson,489334,Craig Stammen,425877,Yadier Molina,R,Austin Nola,543592,3,6,4,True,2020-09-30,Stolen,2B
4,2B,3B,Stolen Base 3B,502054,Tommy Pham,650893,Génesis Cabrera,543592,Austin Nola,L,Yadier Molina,425877,4,6,6,False,2020-09-30,Stolen,3B

In [9]:
# get runner names
runnerNames = df['runner_name'].unique()
runnerNames

array(['Randal Grichuk', 'Mike Tauchman', 'Dylan Carlson', ...,
       'Ryan Sweeney', 'Maicer Izturis', 'Jonathan Diaz'], dtype=object)

In [10]:
# get individual CSV file for each runner
for i in range(len(runnerNames)):
    csvName = runnerNames[i] + '.csv'
    temp = df[df['runner_name'] == runnerNames[i]]
    temp.to_csv(f'Runner_final/{csvName}')